services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  product_api:
    build: ./product_service
    command: gunicorn --bind 0.0.0.0:8888 project_name.wsgi:application  # เปลี่ยนเป็น gunicorn
    volumes:
      - ./product_service:/code
    ports:
      - "3341:8888"
    env_file:
      - ./.env
    depends_on:
      - db

  user_api:
    build: ./user_service
    command: gunicorn --bind 0.0.0.0:8888 project_name.wsgi:application  # เปลี่ยนเป็น gunicorn
    volumes:
      - ./user_service:/code
    ports:
      - "3342:8888"
    env_file:
      - ./.env
    depends_on:
      - db

  front_end:
    build: ./app_frontend
    command: npm run build && npm run start  # เปลี่ยนจาก dev เป็น build + start
    volumes:
      - ./app_frontend:/app
      - /app/node_modules
    ports:
      - "3343:3000"